### ISSUE TITLE
[CQLReplicator on Glue] No space left on device

### ISSUE THREAD

**Issue by hungfaileung** [aws-samples/cql-replicator#114]
**Describe the bug**
During the discovery phase, we got error `java.io.IOException: No space left on device`.

**To Reproduce**
1. Run command './cqlreplicator --state run --tiles 6 --region us-west-2 --src-keyspace xxx --src-table xxx --trg-keyspace xxx --trg-table xxx --landing-zone s3://cql-replicator-xxxxx-us-west-2 --writetime-column xxx --enhanced-monitoring-enabled'
2. See error: `java.io.IOException: No space left on device`

**Expected behavior**
Finish discovery phase and start replication.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by nwheeler81** [comment]
@hungfaileung could you please share the following details: 
- approx. number of the primary keys in the source table
- avg. size of one primary key
- primary key structure (partition keys: type, clustering columns: type)
PS: the CQLReplicator uses `DISK_ONLY` caching strategy and use 1X DPU for the discovery process. 1X has ~34Gb of free space, so that 6 x 34Gb ~ 204Gb but not all free space will be available for the primary keys.

**Comment by hungfaileung** [comment]
- about 400,000,000 primary keys
- sample primary key: `AA |      BBB | 46865a11-f434-4221-aa87-5229b53eb045 |      CCCCCC | PE00X2WRL34YSA2H9VKAWX0QM34N4GYD74R7FAK3M9KHFCGSMX`, assume each char 2 bytes, then would be about 97x2 = 194 bytes
- table structure:
```
CREATE TABLE xxx.xxx (
    aaa text,
    bbb text,
    ccc text,
    ddd text,
    eee text,
    fff bigint,
    ggg text,
    hhh int,
    iii text,
    PRIMARY KEY ((aaa, bbb, ccc), ddd, eee)
) WITH CLUSTERING ORDER BY (ddd ASC, eee ASC)
```

**Comment by hungfaileung** [comment]
Is that a way to estimate the number of tiles to use?

**Comment by hungfaileung** [comment]
Also, seems Glue can offload shuffle storage to S3:
- https://repost.aws/knowledge-center/glue-no-spaces-on-device-error
- https://aws.amazon.com/blogs/big-data/introducing-the-cloud-shuffle-storage-plugin-for-apache-spark/

Is that something would help?

**Comment by nwheeler81** [comment]
@hungfaileung you can try
1/ Open AWS Glue console `CQLReplicator` -> Job details.  Add `--write-shuffle-files-to-s3` in Job parameters and set to `true`
2/  Find `--conf` and at the end of `value` add this line `--conf spark.shuffle.glue.s3ShuffleBucket=s3://your-bucket-S3-storage`

**Comment by hungfaileung** [comment]
@nwheeler81 We tried using the above settings and can see files in the s3 shuffle folder, but still getting the same error:
```
2024-02-09 12:58:31,925 ERROR [Executor task launch worker for task 8.34 in stage 2.0 (TID 789)] executor.Executor (Logging.scala:logError(98)): Exception in task 8.34 in stage 2.0 (TID 789)
com.esotericsoftware.kryo.KryoException: java.io.IOException: No space left on device
Serialization trace:
buffers (org.apache.spark.sql.execution.columnar.DefaultCachedBatch)
	at com.esotericsoftware.kryo.io.Output.flush(Output.java:188) ~[kryo-shaded-4.0.2.jar:?]
	at com.esotericsoftware.kryo.io.Output.require(Output.java:164) ~[kryo-shaded-4.0.2.jar:?]
	at com.esotericsoftware.kryo.io.Output.writeBytes(Output.java:251) ~[kryo-shaded-4.0.2.jar:?]
	at com.esotericsoftware.kryo.io.Output.writeBytes(Output.java:237) ~[kryo-shaded-4.0.2.jar:?]
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ByteArraySerializer.write(DefaultArraySerializers.java:49) ~[kryo-shaded-4.0.2.jar:?]
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ByteArraySerializer.write(DefaultArraySerializers.java:38) ~[kryo-shaded-4.0.2.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObjectOrNull(Kryo.java:629) ~[kryo-shaded-4.0.2.jar:?]
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:332) ~[kryo-shaded-4.0.2.jar:?]
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:302) ~[kryo-shaded-4.0.2.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObjectOrNull(Kryo.java:629) ~[kryo-shaded-4.0.2.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:86) ~[kryo-shaded-4.0.2.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508) ~[kryo-shaded-4.0.2.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651) ~[kryo-shaded-4.0.2.jar:?]
	at org.apache.spark.serializer.KryoSerializationStream.writeObject(KryoSerializer.scala:270) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.serializer.SerializationStream.writeAll(Serializer.scala:151) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.serializer.SerializerManager.dataSerializeStream(SerializerManager.scala:177) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$6(BlockManager.scala:1546) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$6$adapted(BlockManager.scala:1544) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.storage.DiskStore.put(DiskStore.scala:87) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1544) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1435) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1499) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1322) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:376) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:327) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.scheduler.Task.run(Task.scala:138) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548) ~[spark-core_2.12-3.3.0-amzn-1.jar:?]
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1517) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551) ~[spark-core_2.12-3.3.0-amzn-1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_392]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_392]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_392]
Caused by: java.io.IOException: No space left on device
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:1.8.0_392]
	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60) ~[?:1.8.0_392]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[?:1.8.0_392]
	at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[?:1.8.0_392]
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211) ~[?:1.8.0_392]
	at org.apache.spark.storage.CountingWritableChannel.write(DiskStore.scala:353) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78) ~[?:1.8.0_392]
	at java.nio.channels.Channels.writeFully(Channels.java:101) ~[?:1.8.0_392]
	at java.nio.channels.Channels.access$000(Channels.java:61) ~[?:1.8.0_392]
	at java.nio.channels.Channels$1.write(Channels.java:174) ~[?:1.8.0_392]
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122) ~[?:1.8.0_392]
	at net.jpountz.lz4.LZ4BlockOutputStream.flushBufferedData(LZ4BlockOutputStream.java:225) ~[lz4-java-1.8.0.jar:?]
	at net.jpountz.lz4.LZ4BlockOutputStream.write(LZ4BlockOutputStream.java:178) ~[lz4-java-1.8.0.jar:?]
	at com.esotericsoftware.kryo.io.Output.flush(Output.java:185) ~[kryo-shaded-4.0.2.jar:?]
	... 49 more

```

**Comment by nwheeler81** [comment]
> * about 400,000,000 primary keys
> * sample primary key: `AA |      BBB | 46865a11-f434-4221-aa87-5229b53eb045 |      CCCCCC | PE00X2WRL34YSA2H9VKAWX0QM34N4GYD74R7FAK3M9KHFCGSMX`, assume each char 2 bytes, then would be about 97x2 = 194 bytes
> * table structure:
> 
> ```
> CREATE TABLE xxx.xxx (
>     aaa text,
>     bbb text,
>     ccc text,
>     ddd text,
>     eee text,
>     fff bigint,
>     ggg text,
>     hhh int,
>     iii text,
>     PRIMARY KEY ((aaa, bbb, ccc), ddd, eee)
> ) WITH CLUSTERING ORDER BY (ddd ASC, eee ASC)
> ```

400,000,000 primary keys x 200 bytes ~ 75GB, 6 tiles ~ 210GB should be enough space, but I would use 8 tiles to handle overheads.


> buffers (org.apache.spark.sql.execution.columnar.DefaultCachedBatch) I would try to double `spark.kryoserializer.buffer.max.mb` 128mb to 256mb in `--conf` section.

**Comment by hungfaileung** [comment]
@nwheeler81 Thanks, we will try with more tiles.

**Comment by nwheeler81** [comment]
> @nwheeler81 Thanks, we will try with more tiles.

before running again with the higher number of tiles, remove S3 folder s3://bucket/your_ks/your_tbl and delete referencing records from Keyspaces `migration.ledger` by executing `delete from migration.ledger where ks=your_ks and tbl=your_tbl`

**Comment by hungfaileung** [comment]
@nwheeler81 Yep, thanks for reminding.

**Comment by nwheeler81** [comment]
> @nwheeler81 We tried using the above settings and can see files in the s3 shuffle folder, but still getting the same error:
> 
> ```
> 2024-02-09 12:58:31,925 ERROR [Executor task launch worker for task 8.34 in stage 2.0 (TID 789)] executor.Executor (Logging.scala:logError(98)): Exception in task 8.34 in stage 2.0 (TID 789)
> com.esotericsoftware.kryo.KryoException: java.io.IOException: No space left on device
> Serialization trace:
> buffers (org.apache.spark.sql.execution.columnar.DefaultCachedBatch)
> 	at com.esotericsoftware.kryo.io.Output.flush(Output.java:188) ~[kryo-shaded-4.0.2.jar:?]
> 	at com.esotericsoftware.kryo.io.Output.require(Output.java:164) ~[kryo-shaded-4.0.2.jar:?]
> 	at com.esotericsoftware.kryo.io.Output.writeBytes(Output.java:251) ~[kryo-shaded-4.0.2.jar:?]
> 	at com.esotericsoftware.kryo.io.Output.writeBytes(Output.java:237) ~[kryo-shaded-4.0.2.jar:?]
> 	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ByteArraySerializer.write(DefaultArraySerializers.java:49) ~[kryo-shaded-4.0.2.jar:?]
> 	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ByteArraySerializer.write(DefaultArraySerializers.java:38) ~[kryo-shaded-4.0.2.jar:?]
> 	at com.esotericsoftware.kryo.Kryo.writeObjectOrNull(Kryo.java:629) ~[kryo-shaded-4.0.2.jar:?]
> 	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:332) ~[kryo-shaded-4.0.2.jar:?]
> 	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:302) ~[kryo-shaded-4.0.2.jar:?]
> 	at com.esotericsoftware.kryo.Kryo.writeObjectOrNull(Kryo.java:629) ~[kryo-shaded-4.0.2.jar:?]
> 	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:86) ~[kryo-shaded-4.0.2.jar:?]
> 	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508) ~[kryo-shaded-4.0.2.jar:?]
> 	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651) ~[kryo-shaded-4.0.2.jar:?]
> 	at org.apache.spark.serializer.KryoSerializationStream.writeObject(KryoSerializer.scala:270) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.serializer.SerializationStream.writeAll(Serializer.scala:151) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.serializer.SerializerManager.dataSerializeStream(SerializerManager.scala:177) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$6(BlockManager.scala:1546) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$6$adapted(BlockManager.scala:1544) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.storage.DiskStore.put(DiskStore.scala:87) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1544) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1435) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1499) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1322) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:376) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:327) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.scheduler.Task.run(Task.scala:138) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548) ~[spark-core_2.12-3.3.0-amzn-1.jar:?]
> 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1517) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551) ~[spark-core_2.12-3.3.0-amzn-1.jar:?]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_392]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_392]
> 	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_392]
> Caused by: java.io.IOException: No space left on device
> 	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:1.8.0_392]
> 	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60) ~[?:1.8.0_392]
> 	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[?:1.8.0_392]
> 	at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[?:1.8.0_392]
> 	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211) ~[?:1.8.0_392]
> 	at org.apache.spark.storage.CountingWritableChannel.write(DiskStore.scala:353) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
> 	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78) ~[?:1.8.0_392]
> 	at java.nio.channels.Channels.writeFully(Channels.java:101) ~[?:1.8.0_392]
> 	at java.nio.channels.Channels.access$000(Channels.java:61) ~[?:1.8.0_392]
> 	at java.nio.channels.Channels$1.write(Channels.java:174) ~[?:1.8.0_392]
> 	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122) ~[?:1.8.0_392]
> 	at net.jpountz.lz4.LZ4BlockOutputStream.flushBufferedData(LZ4BlockOutputStream.java:225) ~[lz4-java-1.8.0.jar:?]
> 	at net.jpountz.lz4.LZ4BlockOutputStream.write(LZ4BlockOutputStream.java:178) ~[lz4-java-1.8.0.jar:?]
> 	at com.esotericsoftware.kryo.io.Output.flush(Output.java:185) ~[kryo-shaded-4.0.2.jar:?]
> 	... 49 more
> ```
probably, `s3 shuffle` doesn't work b/c the CQLReplicator uses Vanilla Spark instead of Glue context in the discovery stage.
