### ISSUE TITLE
[CQLReplicator on Glue] only insert of new row being replicate, update and delete don't get replicate

### ISSUE THREAD

**Issue by frozensky** [aws-samples/cql-replicator#79]
I am testing out the tool to migrate data from datacenter cassandra to AWS keyspaces. 
I only see insert new rows are being replicate into keyspaces, both update and delete didn't get replicate 

my test cases
1, insert new row - replicated
2, update row - not replicate
3, delete row - not replicate
4, stop cqlreplicator, insert row and update the same row (2 steps), start cqlreplicator - both replicated

**Comment by nwheeler81** [comment]
[UPDATE op] in order to enable updates in the target table, you need to add `--writetime-column regular_column` parameter to your run command, e.g., `./cqlreplicator --state run --tiles 2 --writetime-column reg_column --landing-zone s3://cql-replicator-1234567890-us-east-1 --src-keyspace ks1 --src-table tbl1 --trg-keyspace ks1 --trg-table tbl1 --region us-east-1`.
Note: regular column is not part of the primary key, and should be updated, currently cqlreplicator doesn't support multiple regular columns.
[DELETE op] currently cqlreplicator doesn't support DELETEs, but this feature will be available in Feb 2024.

**Comment by frozensky** [comment]
thank you for the detail response 
we have multiple regular columns that the service/app update frequently, any suggest or options that we can try ?

**Comment by nwheeler81** [comment]
Do you have one or more columns in your source table that are constantly updated, e.g., `status`, `dt_updated`, and etc. if you have, use one of them to replicate updates `--writetime-column dt_updated` or  `--writetime-column status`, `cqlreplicator` updates all columns in your target table if your writetime-column in the source table updated.

**Comment by frozensky** [comment]
I am testing the --writetime-column and looks like the discovery job ran ok, but the replicator job error out with the following error 

```
2024-01-26 02:03:30,080 ERROR [spark-listener-group-shared] glueexceptionanalysis.GlueExceptionAnalysisListener (Logging.scala:logError(9)): [Glue Exception Analysis] 
{
    "Event": "GlueExceptionAnalysisTaskFailed",
    "Timestamp": 1706234610074,
    "Failure Reason": "Error decoding JSON value for adventure: Value '' is not a valid blob representation: String representation of blob is missing 0x prefix: ",
    "Stack Trace": [
```

**Comment by nwheeler81** [comment]
is that the binary column? Could you share your masked table schema?

**Comment by frozensky** [comment]
here is the table schema from source 
```
cqlsh> describe table personalcatalog.my_movies;

CREATE TABLE personalcatalog.my_movies (
    accountid text PRIMARY KEY,
    a_bucket blob,
    action blob,
    adventure blob,
    animation blob,
    avod blob,
    b_bucket blob,
    c_bucket blob,
    comedy blob,
    crime_thrillers blob,
    d_bucket blob,
    documentary blob,
    drama blob,
    e_bucket blob,
    f_bucket blob,
    fantasy blob,
    g_bucket blob,
    greater_than_60_pct blob,
    greater_than_80_pct blob,
    h_bucket blob,
    historical blob,
    horror blob,
    i_bucket blob,
    independent blob,
    international blob,
    j_bucket blob,
    k_bucket blob,
    kids_family blob,
    l_bucket blob,
    m_bucket blob,
    modification_time timestamp,
    music_musical blob,
    n_bucket blob,
    numeric_bucket blob,
    o_bucket blob,
    other blob,
    p_bucket blob,
    purchase_time_bucket_1 text,
    purchase_time_bucket_10 text,
    purchase_time_bucket_2 text,
    purchase_time_bucket_3 text,
    purchase_time_bucket_4 text,
    purchase_time_bucket_5 text,
    purchase_time_bucket_6 text,
    purchase_time_bucket_7 text,
    purchase_time_bucket_8 text,
    purchase_time_bucket_9 text,
    q_bucket blob,
    r_bucket blob,
    reality blob,
    rentals text,
    romance blob,
    s_bucket blob,
    sci_fi blob,
    special_char_bucket blob,
    sports blob,
    superheroes blob,
    suspense blob,
    t_bucket blob,
    total_count int,
    u_bucket blob,
    v_bucket blob,
    w_bucket blob,
    western blob,
    x_bucket blob,
    y_bucket blob,
    z_bucket blob
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND speculative_retry = '99PERCENTILE';

```

**Comment by nwheeler81** [comment]
I reproduced your error in `CQLSH` if the blob column value is empty:
`localhost@cqlsh:ks> create table test1 (pk int PRIMARY KEY, bin blob ) ;`
`localhost@cqlsh:ks> insert into test1 JSON '{"pk": 1, "bin":""}';`
`InvalidRequest: Error from server: code=2200 [Invalid query] message="Error decoding JSON value for bin: Value '' is not a valid blob representation: String representation of blob is missing 0x prefix: "`

**Comment by nwheeler81** [comment]
@frozensky Added support for DELETEs and fixed the issue with JSON serialization with "0x" empty blob columns. Could you please validate.
 1/ Run `--state cleanup`
 2/ Clone the git repository
 3/ Run `--state run`
 4/ Validate `--state stats`

**Comment by frozensky** [comment]
thank you for the quick turn around, I did `--state cleanup` (verify s3 bucket is empty, glue notebook and connector were deleted, keyspaces migration was deleted) git pull (main branch), run `--state init` and `--state run`, see the following error in the log 
```
2024-01-28 00:26:35,087 ERROR [Executor task launch worker for task 1.3 in stage 3.0 (TID 13)] executor.Executor (Logging.scala:logError(98)): Exception in task 1.3 in stage 3.0 (TID 13)
com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: Error decoding JSON value for sports: Value '' is not a valid blob representation: String representation of blob is missing 0x prefix: 
	at com.datastax.oss.driver.api.core.servererrors.InvalidQueryException.copy(InvalidQueryException.java:48) ~[spark-cassandra-connector-assembly_2.12-3.4.1.jar:3.4.1]
	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149) ~[spark-cassandra-connector-assembly_2.12-3.4.1.jar:3.4.1]
	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:53) ~[spark-cassandra-connector-assembly_2.12-3.4.1.jar:3.4.1]
	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:30) ~[spark-cassandra-connector-assembly_2.12-3.4.1.jar:3.4.1]
	at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:230) ~[spark-cassandra-connector-assembly_2.12-3.4.1.jar:3.4.1]
	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:54) ~[spark-cassandra-connector-assembly_2.12-3.4.1.jar:3.4.1]
	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:78) ~[spark-cassandra-connector-assembly_2.12-3.4.1.jar:3.4.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_392]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_392]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_392]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_392]
	at com.datastax.spark.connector.cql.SessionProxy.invoke(SessionProxy.scala:43) ~[spark-cassandra-connector-assembly_2.12-3.4.1.jar:3.4.1]
	at com.sun.proxy.$Proxy71.execute(Unknown Source) ~[?:?]
	at GlueApp$.$anonfun$main$20(CQLReplicator.scala:336) ~[CQLReplicator.scala.jar:?]
	at io.github.resilience4j.retry.Retry.lambda$decorateSupplier$2(Retry.java:213) ~[resilience4j-retry-1.7.1.jar:1.7.1]
	at GlueApp$.$anonfun$main$19(CQLReplicator.scala:336) ~[CQLReplicator.scala.jar:?]
	at com.datastax.spark.connector.cql.CassandraConnector.$anonfun$withSessionDo$1(CassandraConnector.scala:104) ~[spark-cassandra-connector-assembly_2.12-3.4.1.jar:3.4.1]
	at com.datastax.spark.connector.cql.CassandraConnector.closeResourceAfterUse(CassandraConnector.scala:121) ~[spark-cassandra-connector-assembly_2.12-3.4.1.jar:3.4.1]
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:103) ~[spark-cassandra-connector-assembly_2.12-3.4.1.jar:3.4.1]
	at GlueApp$.$anonfun$main$18(CQLReplicator.scala:333) ~[CQLReplicator.scala.jar:?]
	at com.datastax.spark.connector.cql.CassandraConnector.$anonfun$withSessionDo$1(CassandraConnector.scala:104) ~[spark-cassandra-connector-assembly_2.12-3.4.1.jar:3.4.1]
	at com.datastax.spark.connector.cql.CassandraConnector.closeResourceAfterUse(CassandraConnector.scala:121) ~[spark-cassandra-connector-assembly_2.12-3.4.1.jar:3.4.1]
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:103) ~[spark-cassandra-connector-assembly_2.12-3.4.1.jar:3.4.1]
	at GlueApp$.$anonfun$main$17(CQLReplicator.scala:327) ~[CQLReplicator.scala.jar:?]
	at scala.collection.Iterator.foreach(Iterator.scala:943) ~[scala-library-2.12.15.jar:?]
	at scala.collection.Iterator.foreach$(Iterator.scala:943) ~[scala-library-2.12.15.jar:?]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431) ~[scala-library-2.12.15.jar:?]
	at GlueApp$.$anonfun$main$16(CQLReplicator.scala:323) ~[CQLReplicator.scala.jar:?]
	at GlueApp$.$anonfun$main$16$adapted(CQLReplicator.scala:306) ~[CQLReplicator.scala.jar:?]
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1011) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1011) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2269) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.scheduler.Task.run(Task.scala:138) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548) ~[spark-core_2.12-3.3.0-amzn-1.jar:?]
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1517) ~[spark-core_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551) ~[spark-core_2.12-3.3.0-amzn-1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_392]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_392]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_392]
```

**Comment by frozensky** [comment]
Thank you for the quick turn around, I see the replicator running now 
I am going to replicate more tables and run some test for the update and delete.  

```
./cqlreplicator --state run --tiles 2 --writetime-column modification_time --landing-zone s3://hnt-cqlreplicator-stg --region us-west-1 --src-keyspace personalcatalog --src-table my_movies --trg-keyspace stg_hnt_personalcatalog --trg-table my_movies --inc-traffic
·······································································
[2024-01-27T16:37:43-08:00] OS: Darwin
[2024-01-27T16:37:43-08:00] Incremental traffic for the historical workload is enabled
[2024-01-27T16:37:43-08:00] Incremental period: 240 seconds
[2024-01-27T16:37:43-08:00] Starting discovery process...
[2024-01-27T16:37:43-08:00] TILES: 2
[2024-01-27T16:37:43-08:00] SOURCE: personalcatalog.my_movies
[2024-01-27T16:37:43-08:00] TARGET: stg_hnt_personalcatalog.my_movies
[2024-01-27T16:37:43-08:00] LANDING ZONE: s3://hnt-cqlreplicator-stg
[2024-01-27T16:37:43-08:00] WRITE TIME COLUMN: modification_time
[2024-01-27T16:37:43-08:00] TTL COLUMN: None
[2024-01-27T16:37:43-08:00] ROWS PER DPU: 250000
[2024-01-27T16:37:43-08:00] Checking if the discovery job is already running...
{

    "DeleteMarker": true,
    "VersionId": "null"
}
[2024-01-27T16:37:45-08:00] Starting the discovery job...
[2024-01-27T16:39:26-08:00] Average primary keys per tile is 127117
{
    "DeleteMarker": true,
    "VersionId": "null"
}
{tarting Glue Jobs : [||||||||||||||||||||--------------------] 50.00%
    "DeleteMarker": true,
    "VersionId": "null"
}
Starting Glue Jobs : [||||||||||||||||||||||||||||||||||||||||] 100.00% - COMPLETED
[2024-01-27T16:47:34-08:00] Started jobs: jr_18cdce4b61f938848e2d005db7c103d044045990d2d2c9fe5285f4b7831b9b91 jr_3edc5591f56a7b64aff12f06e2e805d82d855f4e497956027656c7f63c3eeea5 jr_e945898cbe3b6bd5aa43b4b3f78371379d53b779dbf1f0c4ef6d09ff96b7d72b
```

```
$ ./cqlreplicator --state stats --landing-zone s3://hnt-cqlreplicator-stg --src-keyspace personalcatalog --src-tabl
e my_movies
·······································································
[2024-01-27T16:47:57-08:00] OS: Darwin
[2024-01-27T16:48:05-08:00] Discovered rows in personalcatalog.my_movies is 254274
[2024-01-27T16:48:05-08:00] Replicated rows in ks_test_cql_replicator.test_cql_replicator is 0
```

**Comment by frozensky** [comment]
confirm UPDATEs and DELETEs are being replicate, testing more tables to confirm
